### ISSUE TITLE
cannot import name 'qconfig' from 'qcatsweeper'

### ISSUE THREAD

**Issue by omarcostahamido** [desireevl/awesome-quantum-computing#31]
if you would like to look into it.

<p>
<details><summary>term</summary>

```
$  python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import qcatsweeper.gui as QGUI
  File "/Users/omar/Documents/QuID/day 4/mine/quantum-catsweeper/qcatsweeper/gui.py", line 4, in <module>
    import qcatsweeper.quantum_logic as ql
  File "/Users/omar/Documents/QuID/day 4/mine/quantum-catsweeper/qcatsweeper/quantum_logic.py", line 3, in <module>
    from qcatsweeper import qconfig
ImportError: cannot import name 'qconfig' from 'qcatsweeper' (/Users/omar/Documents/QuID/day 4/mine/quantum-catsweeper/qcatsweeper/__init__.py)
```

</details>
</p>

**Comment by desireevl** [comment]
Hey Omar, sorry for the delayed response, I didn't see this earlier. Qconfig was the file that was used to store my SSH key for accessing the IBM Q computer (you would need to create your own personal file) however this is now an outdated method. I believe there might be other sections of the code which are also outdated due to Qiskits latest updates :(

**Comment by omarcostahamido** [comment]
Hi Desiree,

I see. In any case, given that you're still using pyxel for your recent
projects (i.e. Qiskit Camp) I would like to try out one of your games at
some point.

Best,
OCH

Em qua, 18 de set de 2019 às 22:15, Desiree Vogt-Lee <
notifications@github.com> escreveu:
